CREATE TABLE IF NOT EXISTS stage_countries (
    name varchar(256),
    code varchar(10),
    flag varchar(256)
);

CREATE TABLE IF NOT EXISTS stage_leagues (
    league_id int,
    league_name varchar(256),
    league_type varchar(50),
    league_logo varchar(256),
    country_name varchar(256),
    country_code varchar(10),
    country_flag varchar(256),
    seasons_year int,
    seasons_start date,
    seasons_end date,
    seasons_current boolean,
    seasons_coverage_fixtures_events boolean,
    seasons_coverage_fixtures_lineups boolean,
    seasons_coverage_fixtures_statistics_fixtures boolean,
    seasons_coverage_fixtures_statistics_players boolean,
    seasons_coverage_standings boolean,
    seasons_coverage_players boolean,
    seasons_coverage_top_scorers boolean,
    seasons_coverage_top_assists boolean,
    seasons_coverage_top_cards boolean,
    seasons_coverage_injuries boolean,
    seasons_coverage_predictions boolean,
    seasons_coverage_odds boolean
);

CREATE TABLE IF NOT EXISTS stage_teams (
    team_id int NOT NULL,
    team_name varchar(256),
    team_code varchar(20),
    team_country varchar(256),
    team_founded int,
    team_national boolean,
    team_logo varchar(256),
    venue_id int,
    venue_name varchar(256),
    venue_address varchar(256),
    venue_city varchar(256),
    venue_capacity int,
    venue_surface varchar(256),
    venue_image varchar(256),
    season int, 
    league_id int
);

CREATE TABLE IF NOT EXISTS stage_players (
    player_id INT,
    player_name VARCHAR(256),
    player_firstname VARCHAR(256),
    player_lastname VARCHAR(256),
    player_age INT,
    player_birth_date DATE,
    player_birth_place VARCHAR(256),
    player_birth_country VARCHAR(256),
    player_nationality VARCHAR(256),
    player_height VARCHAR(10),
    player_weight VARCHAR(10),
    player_injured BOOLEAN,
    player_photo VARCHAR(256),
    statistics_team_id INT,
    statistics_team_name VARCHAR(256),
    statistics_team_logo VARCHAR(256),
    statistics_league_id INT,
    statistics_league_name VARCHAR(256),
    statistics_league_country VARCHAR(256),
    statistics_league_logo VARCHAR(256),
    statistics_league_flag VARCHAR(256),
    statistics_league_season INT,
    statistics_games_appearences INT,
    statistics_games_lineups INT,
    statistics_games_minutes INT,
    statistics_games_number INT,
    statistics_games_position VARCHAR(256),
    statistics_games_rating FLOAT,
    statistics_games_captain BOOLEAN,
    statistics_substitutes_in INT,
    statistics_substitutes_out INT,
    statistics_substitutes_bench INT,
    statistics_shots_total INT,
    statistics_shots_on INT,
    statistics_goals_total INT,
    statistics_goals_conceded INT,
    statistics_goals_assists INT,
    statistics_goals_saves INT,
    statistics_passes_total INT,
    statistics_passes_key INT,
    statistics_passes_accuracy INT,
    statistics_tackles_total INT,
    statistics_tackles_blocks INT,
    statistics_tackles_interceptions INT,
    statistics_duels_total INT,
    statistics_duels_won INT,
    statistics_dribbles_attempts INT,
    statistics_dribbles_success INT,
    statistics_dribbles_past INT,
    statistics_fouls_drawn INT,
    statistics_fouls_committed INT,
    statistics_cards_yellow INT,
    statistics_cards_yellowred INT,
    statistics_cards_red INT,
    statistics_penalty_won INT,
    statistics_penalty_commited INT,
    statistics_penalty_scored INT,
    statistics_penalty_missed INT,
    statistics_penalty_saved INT
);

CREATE TABLE IF NOT EXISTS stage_fixtures (
    fixture_date VARCHAR(256),
    fixture_id INT,
    fixture_periods_first INT,
    fixture_periods_second INT,
    fixture_referee VARCHAR(256),
    fixture_status_elapsed INT,
    fixture_status_long VARCHAR(256),
    fixture_status_short VARCHAR(256),
    fixture_timestamp INT,
    fixture_timezone VARCHAR(256),
    fixture_venue_city VARCHAR(256),
    fixture_venue_id INT,
    fixture_venue_name VARCHAR(256),
    goals_away INT,
    goals_home INT,
    league_country VARCHAR(256),
    league_flag VARCHAR(256),
    league_id INT,
    league_logo VARCHAR(256),
    league_name VARCHAR(256),
    league_round VARCHAR(256),
    league_season INT,
    score_extratime_away INT,
    score_extratime_home INT,
    score_fulltime_away INT,
    score_fulltime_home INT,
    score_halftime_away INT,
    score_halftime_home INT,
    score_penalty_away INT,
    score_penalty_home INT,
    teams_away_id INT,
    teams_away_logo VARCHAR(256),
    teams_away_name VARCHAR(256),
    teams_away_winner BOOLEAN,
    teams_home_id INT,
    teams_home_logo VARCHAR(256),
    teams_home_name VARCHAR(256),
    teams_home_winner BOOLEAN
);

CREATE TABLE IF NOT EXISTS stage_lineups (
    formation VARCHAR(256),
    team_id INT,
    team_name VARCHAR(256),
    team_logo VARCHAR(256),
    team_colors VARCHAR(256),
    coach_id INT,
    coach_name VARCHAR(256),
    coach_photo VARCHAR(256),
    fixture_id INT,
    lineup_player_id INT,
    lineup_player_name VARCHAR(256),
    lineup_player_number INT,
    lineup_player_pos VARCHAR(256),
    lineup_player_grid VARCHAR(256),
    lineup_type VARCHAR(256),
    season INT
);

CREATE TABLE IF NOT EXISTS stage_standings (
    league_id INT,
    league_name VARCHAR(256),
    league_country VARCHAR(256),
    league_logo VARCHAR(256),
    league_flag VARCHAR(256),
    league_season INT,
    league_standings_rank INT,
    league_standings_points INT,
    league_standings_goalsDiff INT,
    league_standings_group VARCHAR(256),
    league_standings_form VARCHAR(256),
    league_standings_status VARCHAR(256),
    league_standings_description VARCHAR(256),
    league_standings_update VARCHAR(256),
    league_standings_team_id INT,
    league_standings_team_name VARCHAR(256),
    league_standings_team_logo VARCHAR(256),
    league_standings_all_played INT,
    league_standings_all_win INT,
    league_standings_all_draw INT,
    league_standings_all_lose INT,
    league_standings_all_goals_for INT,
    league_standings_all_goals_against INT,
    league_standings_home_played INT,
    league_standings_home_win INT,
    league_standings_home_draw INT,
    league_standings_home_lose INT,
    league_standings_home_goals_for INT,
    league_standings_home_goals_against INT,
    league_standings_away_played INT,
    league_standings_away_win INT,
    league_standings_away_draw INT,
    league_standings_away_lose INT,
    league_standings_away_goals_for INT,
    league_standings_away_goals_against INT,
    league_standings_index INT
);

CREATE TABLE IF NOT EXISTS stage_statistics (
    team_id INT,
    team_name VARCHAR(256),
    team_logo VARCHAR(256),
    fixture_id INT,
    Shots_on_Goal INT,
    Shots_off_Goal INT,
    Total_Shots INT,
    Blocked_Shots INT,
    Shots_insidebox INT,
    Shots_outsidebox INT,
    Fouls INT,
    Corner_Kicks INT,
    Offsides INT,
    Ball_Possession VARCHAR(256),
    Yellow_Cards INT,
    Red_Cards INT,
    Goalkeeper_Saves INT,
    Total_passes INT,
    Passes_accurate INT,
    Passes_percentage VARCHAR(256)
);

CREATE TABLE IF NOT EXISTS public.countries (
	code varchar(10),
	name varchar(256) NOT NULL,
	flag varchar(256),
	CONSTRAINT countries_pkey PRIMARY KEY (name)
);

CREATE TABLE IF NOT EXISTS public.leagues (
	id int NOT NULL,
	name varchar(256),
	type varchar(20),
    logo varchar(256),
    country_name varchar(256),
	seasons_year int not null,
    seasons_start date,
    seasons_end date,
    seasons_current boolean, 
    CONSTRAINT leagues_pkey PRIMARY KEY (id, seasons_year)
);

CREATE TABLE IF NOT EXISTS public.teams (
	id int NOT NULL,
    season int NOT NULL, 
	name varchar(256),
	code varchar(20),
	country varchar(256),
    league_id int,
	founded int,
	national boolean,
	logo varchar(256),
	venue_id int,
	CONSTRAINT teams_pkey PRIMARY KEY (id, season, league_id)
);

CREATE TABLE IF NOT EXISTS public.venues (
	id int NOT NULL,
    season int NOT NULL, 
	name varchar(256),
	address varchar(256),
	city varchar(256),
	capacity int,
	surface varchar(20),
	image varchar(256),
	CONSTRAINT venues_pkey PRIMARY KEY (id, season)
);

CREATE TABLE IF NOT EXISTS public.players (
	id int NOT NULL,
	name varchar(100),
    firstname varchar(50),
    lastname varchar(50),
	birth date,
	birth_place varchar(256),
	birth_country varchar(256),
	nationality varchar(256),
    height varchar(50),
    weight varchar(50),
    injured bool,
    photo varchar(256),
    CONSTRAINT players_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.fixtures (
    id int NOT NULL,
    fixture_date date,
    fixture_time time,
    periods_first INT,
    periods_second INT,
    referee VARCHAR(256),
    status_elapsed INT,
    status_long VARCHAR(256),
    status_short VARCHAR(256),
    timestamp INT,
    timezone VARCHAR(256),
    venue_id INT,
    goals_away INT,
    goals_home INT,
    league_id INT,
    league_round VARCHAR(256),
    league_season INT,
    score_extratime_away INT,
    score_extratime_home INT,
    score_fulltime_away INT,
    score_fulltime_home INT,
    score_halftime_away INT,
    score_halftime_home INT,
    score_penalty_away INT,
    score_penalty_home INT,
    teams_away_id INT,
    teams_away_winner BOOLEAN,
    teams_home_id INT,
    teams_home_winner BOOLEAN,
    CONSTRAINT fixtures_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.lineups (
    formation VARCHAR(256),
    team_id INT,
    season INT,
    coach_id INT,
    coach_name VARCHAR(256),
    coach_photo VARCHAR(256),
    fixture_id INT,
    player_id INT,
    player_number INT,
    player_pos VARCHAR(256),
    player_grid VARCHAR(256),
    lineup_type VARCHAR(256),
    CONSTRAINT lineups_pkey PRIMARY KEY (fixture_id, team_id, player_id)
);

CREATE TABLE IF NOT EXISTS public.player_statistics (
    player_id int NOT NULL,
	team_id int NOT NULL,
    league_id int NOT NULL,
	league_season int NOT NULL,
    venue_id int, 
    game_appearences int,
    game_lineups int,
    game_minutes int,
    game_number int,
    game_position varchar(50),
    game_rating varchar(50),
    game_captain bool,
    substitute_in int,
	substitute_out int,
	substitute_bench int,
	shot_total int,
	shot_on int,
    goal_total int,
    goal_conceded int,
    goal_assists int,
    goal_saves int,
    pass_total int,
    pass_key int,
    pass_accuracy int,
    tackle_total int,
    tackle_blocks int,
    tackle_interceptions int,
    duel_total int,
    duel_won int,
    dribble_attempts int,
    dribble_success int,
    dribble_past int,
    foul_drawn int,
    foul_committed int,
    card_yellow int,
    card_yellowred int,
    card_red int,
    penalty_won int,
    penalty_commited int,
    penalty_scored int,
    penalty_missed int,
    penalty_saved int,
    CONSTRAINT player_statistics_pkey PRIMARY KEY (player_id, team_id, league_id, league_season)
);

CREATE TABLE IF NOT EXISTS public.match_statistics (
    team_id INT,
    fixture_id INT,
    league_id INT,
    league_season INT, 
    venue_id INT,
    Shots_on_Goal INT,
    Shots_off_Goal INT,
    Total_Shots INT,
    Blocked_Shots INT,
    Shots_insidebox INT,
    Shots_outsidebox INT,
    Fouls INT,
    Corner_Kicks INT,
    Offsides INT,
    Ball_Possession VARCHAR(256),
    Yellow_Cards INT,
    Red_Cards INT,
    Goalkeeper_Saves INT,
    Total_passes INT,
    Passes_accurate INT,
    Passes_percentage VARCHAR(256),
    CONSTRAINT statistics_pkey PRIMARY KEY (fixture_id, team_id)
);

CREATE TABLE IF NOT EXISTS league_standings (
    league_id INT NOT NULL,
    league_season INT NOT NULL,
    team_id INT NOT NULL,
    venue_id INT, 
    standings_index INT NOT NULL,
    rank INT,
    points INT,
    goalsDiff INT,
    standings_group VARCHAR(256),
    form VARCHAR(256),
    status VARCHAR(256),
    description VARCHAR(256),
    update_date date,
    update_time time,
    all_played INT,
    all_win INT,
    all_draw INT,
    all_lose INT,
    all_goals_for INT,
    all_goals_against INT,
    home_played INT,
    home_win INT,
    home_draw INT,
    home_lose INT,
    home_goals_for INT,
    home_goals_against INT,
    away_played INT,
    away_win INT,
    away_draw INT,
    away_lose INT,
    away_goals_for INT,
    away_goals_against INT,
    CONSTRAINT standings_pkey PRIMARY KEY (league_id, league_season, standings_index, team_id)
);